In [1]:
import time
import graphviz
import pandas as pd
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import sklearn.metrics
from sklearn import tree
from sklearn.metrics import accuracy_score

In [2]:
start_time = time.time()

In [3]:
df = pd.read_csv('PREPARED.csv',sep=",")

In [4]:
df

,AGE,GENDER,LUNG DISEASE,HEART DISEASE,GASTRIC DISEASE,LOCALITY,STATUS,AFFECTED
0,51,F,1,0,0,CITY,DISEASED,0
1,45,M,1,1,1,CITY,DISEASED,1
2,21,F,0,1,0,CITY,DISEASED,1
3,56,M,0,1,0,VILLAGE,RECOVERED,1
4,41,F,1,0,1,CITY,DISEASED,0
5,15,M,1,0,1,CITY,DISEASED,0
6,12,M,0,1,0,VILLAGE,RECOVERED,1
7,51,F,0,1,1,VILLAGE,DISEASED,1
8,45,M,1,0,0,CITY,DISEASED,0
9,12,F,0,1,1,CITY,DISEASED,1
10,45,M,1,1,0,CITY,RECOVERED,1
11,84,F,1,0,1,VILLAGE,RECOVERED,0
12,45,F,0,1,0,CITY,DISEASED,1
13,26,M,0,1,1,CITY,RECOVERED,1
14,54,M,1,0,1,VILLAGE,DISEASED,0
15,63,F,1,1,0,VILLAGE,RECOVERED,1
16,65,F,0,0,1,CITY,RECOVERED,0
17,58,M,1,0,1,VILLAGE,DISEASED,0
18,45,M,0,0,0,CITY,DISEASED,0
19,12,F,1,1,1,VILLAGE,RECOVERED,1
20,63,F,1,1,0,CITY,RECOVERED,1
21,52,F,0,0,1,VILLAGE,DISEASED,0
22,15,M,1,1,0,CITY,DISEASED,1
23,96,M,0,1,1,VILLAGE,RECOVERED,1
24,41,F,1,0,1,CITY,DISEASED,0
25,12,M,0,1,0,VILLAGE,RECOVERED,1
26,52,F,1,0,0,VILLAGE,DISEASED,0
27,20,M,1,1,1,CITY,RECOVERED,1
28,30,F,1,0,0,VILLAGE,DISEASED,0
29,41,M,0,1,1,CITY,RECOVERED,1
...,...,...,...,...,...,...,...,...
3586,42,F,1,0,0,VILLAGE,DISEASED,1
3587,23,F,0,1,0,CITY,RECOVERED,0
3588,23,F,0,1,0,VILLAGE,DISEASED,0
3589,27,F,0,1,0,CITY,DISEASED,0
3590,28,M,1,0,0,VILLAGE,DISEASED,1
3591,27,M,0,0,0,VILLAGE,DISEASED,0
3592,22,M,1,0,1,VILLAGE,RECOVERED,1
3593,25,F,1,0,0,CITY,RECOVERED,0
3594,22,F,0,1,0,CITY,DISEASED,1
3595,41,M,1,1,0,VILLAGE,DISEASED,0
3596,51,F,1,0,0,VILLAGE,RECOVERED,1
3597,27,M,0,0,1,VILLAGE,RECOVERED,0
3598,54,F,0,0,0,CITY,RECOVERED,0
3599,22,M,1,1,0,CITY,RECOVERED,0
3600,43,M,0,0,1,VILLAGE,RECOVERED,0
3601,40,F,0,1,0,VILLAGE,DISEASED,1
3602,40,M,0,0,0,CITY,RECOVERED,0
3603,24,F,1,1,1,CITY,DISEASED,1
3604,70,M,0,1,1,VILLAGE,DISEASED,1
3605,40,F,0,0,1,VILLAGE,RECOVERED,0
3606,43,F,1,0,0,CITY,RECOVERED,0
3607,45,M,0,1,0,CITY,RECOVERED,1
3608,49,M,0,0,1,CITY,RECOVERED,0
3609,21,F,1,1,0,VILLAGE,DISEASED,1
3610,47,F,1,0,1,CITY,DISEASED,0
3611,22,M,1,0,1,CITY,DISEASED,1
3612,68,M,0,1,1,CITY,DISEASED,1
3613,31,F,0,0,0,VILLAGE,RECOVERED,0
3614,53,F,1,0,0,VILLAGE,RECOVERED,0
3615,25,F,1,1,0,VILLAGE,DISEASED,1

In [5]:
df_numeric_only = df._get_numeric_data()

In [6]:
df_numeric_only

      AGE  LUNG DISEASE  HEART DISEASE  GASTRIC DISEASE  AFFECTED
0      51             1              0                0         0
1      45             1              1                1         1
2      21             0              1                0         1
3      56             0              1                0         1
4      41             1              0                1         0
5      15             1              0                1         0
6      12             0              1                0         1
7      51             0              1                1         1
8      45             1              0                0         0
9      12             0              1                1         1
10     45             1              1                0         1
11     84             1              0                1         0
12     45             0              1                0         1
13     26             0              1                1         1
14     54             1              0                1         0
15     63             1              1                0         1
16     65             0              0                1         0
17     58             1              0                1         0
18     45             0              0                0         0
19     12             1              1                1         1
20     63             1              1                0         1
21     52             0              0                1         0
22     15             1              1                0         1
23     96             0              1                1         1
24     41             1              0                1         0
25     12             0              1                0         1
26     52             1              0                0         0
27     20             1              1                1         1
28     30             1              0                0         0
29     41             0              1                1         1
...   ...           ...            ...              ...       ...
3586   42             1              0                0         1
3587   23             0              1                0         0
3588   23             0              1                0         0
3589   27             0              1                0         0
3590   28             1              0                0         1
3591   27             0              0                0         0
3592   22             1              0                1         1
3593   25             1              0                0         0
3594   22             0              1                0         1
3595   41             1              1                0         0
3596   51             1              0                0         1
3597   27             0              0                1         0
3598   54             0              0                0         0
3599   22             1              1                0         0
3600   43             0              0                1         0
3601   40             0              1                0         1
3602   40             0              0                0         0
3603   24             1              1                1         1
3604   70             0              1                1         1
3605   40             0              0                1         0
3606   43             1              0                0         0
3607   45             0              1                0         1
3608   49             0              0                1         0
3609   21             1              1                0         1
3610   47             1              0                1         0
3611   22             1              0                1         1
3612   68             0              1                1         1
3613   31             0              0                0         0
3614   53             1              0                0         0
3615   25             1              1                0         1

[3616 rows x 5 columns]

In [7]:
x = df_numeric_only.values[:, 0:4]
y = df_numeric_only.values[:,4]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.30)

In [10]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2531, 4)
(1085, 4)
(2531,)
(1085,)

In [11]:
features = list(df.columns[:4])

In [12]:
#from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [13]:
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 1, splitter='best')
classifier = classifier.fit(x_train,y_train)

In [14]:
predictions = classifier.predict(x_test)

In [15]:
print(sklearn.metrics.confusion_matrix(y_test, predictions))

[[566  36]
 [ 37 446]]

In [16]:
print("accuracy of training dataset is{:.2f}".format(classifier.score(x_train,y_train)))
print("accuracy of test dataset is {:.2f}".format(classifier.score(x_test,y_test)))

accuracy of training dataset is0.94
accuracy of test dataset is 0.93

In [17]:
print("Error rate is",1- accuracy_score(y_test, predictions, normalize = True))

Error rate is 0.06728110599078341

In [18]:
print("sensitivity is", sklearn.metrics.recall_score(y_test, predictions,labels=None, average =  'micro', sample_weight=None))

sensitivity is 0.9327188940092166

In [19]:
print("specificity is", 1 - sklearn.metrics.recall_score(y_test, predictions,labels=None, average =  'micro', sample_weight=None))

specificity is 0.06728110599078341